name: shop_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  dio: ^4.0.6
  smooth_page_indicator: ^1.0.0+2
  page_transition: "^2.0.9"
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.0.9
  carousel_slider: ^4.1.1
  flutter_native_splash: ^2.2.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.7
flutter_native_splash:
 android: true
 ios: true
 web: true
 image: assets/images/carts.png
 color: "009688"

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding_images/
    - assets/images/
    - assets/lottie_json/
  fonts:
   - family: font_app
     fonts:
       - asset: assets/font/font.ttf